--PRODUCT_MAST

--1
SELECT COUNT(DISTINCT COMPANY) FROM PRODUCT_MAST

--2
SELECT COUNT(PRODUCT) FROM PRODUCT_MAST
WHERE RATE>20

--3
SELECT COUNT(PRODUCT),COMPANY FROM PRODUCT_MAST
GROUP BY COMPANY

--4
SELECT SUM(COST),PRODUCT FROM product_mast
GROUP BY product
HAVING SUM(COST)>500

--5
SELECT MAX(QTY),COMPANY,PRODUCT FROM product_mast
GROUP BY COMPANY,PRODUCT

--6
SELECT PRODUCT,MAX(QTY)AS MAXIMUM,MIN(QTY)AS MINIMUM,SUM(QTY)AS TOTAL FROM product_mast
GROUP BY product

--7
SELECT AVG(RATE)AS AVERAGE,COMPANY FROM product_mast
GROUP BY company


