--1
select * from deposit

--2
select * from BORROW

--3
select * from CUSTOMERS

--4
select ACTNO,CNAME,AMOUNT FROM DEPOSIT

--5
SELECT LOANNO,AMOUNT FROM BORROW

--6
SELECT * FROM DEPOSIT
WHERE BNAME='ANDHERI'

--7
SELECT ACTNO,AMOUNT FROM DEPOSIT
WHERE ACTNO = 106

--8
SELECT * FROM BORROW 
WHERE AMOUNT > 5000

--9
SELECT CNAME FROM DEPOSIT
WHERE ADATE > '1996-12-1'

--10
SELECT CNAME FROM DEPOSIT
WHERE ACTNO < 105

--11
SELECT CNAME FROM CUSTOMERS
WHERE CITY = 'NAGPUR'
OR CITY = 'DELHI'

--12
SELECT CNAME,BNAME FROM DEPOSIT
WHERE AMOUNT > 4000 
AND  ACTNO < 105

--13
SELECT * FROM BORROW
WHERE AMOUNT BETWEEN 3000 AND 8000

--14
SELECT * FROM DEPOSIT
WHERE BNAME != 'ANDHERI'

--15
SELECT CNAME FROM BORROW
WHERE AMOUNT IS NULL

--16
SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
WHERE BNAME IN ('AJNI','KAROLBAGH','M.G. ROAD')
AND ACTNO < 104

SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
WHERE BNAME = 'AJNI'
OR  BNAME = 'KAROLBAGH'
OR  BNAME = 'M.G. ROAD'

--17
SELECT top 5 * FROM customers


--18
SELECT top 3 * FROM DEPOSIT
WHERE AMOUNT > 1000

--19
SELECT TOP 5 LOANNO,CNAME FROM BORROW
WHERE BNAME != 'ANDHERI'

--20
SELECT DISTINCT CITY FROM CUSTOMERS

--21
SELECT DISTINCT BNAME FROM BRANCH

--22
SELECT * FROM CUSTOMERS 
ORDER BY  CNAME ASC

--23
SELECT * FROM DEPOSIT 
ORDER BY  AMOUNT DESC

--24
SELECT * FROM CUSTOMERS
ORDER BY  CITY DESC

--25
SELECT DISTINCT CNAME AS UNI_BORROWERS FROM BORROW






