--LAB9

--1
 SELECT NAME FROM COMPUTER
 UNION
 SELECT NAME FROM ELECTRICAL 

 --2
 SELECT NAME FROM Computer
UNION ALL
SELECT NAME FROM Electrical

--3
SELECT Name FROM Computer
INTERSECT
SELECT Name FROM Electrical--4SELECT Name FROM Computer
EXCEPTSELECT Name FROM Electrical--5SELECT Name FROM ElectricalEXCEPTSELECT Name FROM Computer--6SELECT * FROM ComputerUNION SELECT * FROM ELECTRICAL  --7SELECT * FROM ELECTRICAL  INTERSECTSELECT * FROM Computer --1SELECT * INTO WorldCup FROM Cricket--2SELECT Name, City INTO T20 FROM Cricket WHERE 1=2--3SELECT * INTO IPL FROM CRICKET WHERE 1<>1--4INSERT INTO IPL SELECT * FROM Cricket WHERE Name LIKE '_A_____%'--5DELETE FROM IPL--6DELETE FROM Cricket WHERE City='jharkhand'--7SP_RENAME 'IPL','IPL2018'--8DROP TABLE T20