--LAB12

--1
CREATE VIEW PERSONAL AS SELECT * FROM STUDENT_12


--2
CREATE VIEW STUDENT_DETAILS AS
SELECT NAME,BRANCH,SPI FROM STUDENT_12

--3
CREATE VIEW ACADEMIC AS
SELECT RNO,NAME,BRANCH FROM STUDENT_12

--4
CREATE VIEW STUDENT_DATA AS
SELECT * FROM STUDENT_12
WHERE BKLOG>2

--5
CREATE VIEW STUDENT_PATTERN AS
SELECT RNO,NAME,BRANCH FROM STUDENT_12
WHERE NAME LIKE '____'

--6
INSERT INTO  ACADEMIC VALUES(107,'MEET','ME')

INSERT INTO ACADEMIC 
SELECT 107,'MEET','ME'

--7
UPDATE STUDENT_DETAILS SET BRANCH='ME' 
WHERE NAME='AMIT'
AND BRANCH='CE'

--8
DELETE FROM ACADEMIC 
WHERE RNO=104

--9
CREATE VIEW CLEAVER_STUDENTS AS
SELECT * FROM STUDENT_12
WHERE SPI > 9.5

--10
CREATE VIEW AVERAGE_STUDENT AS
SELECT * FROM STUDENT_12
WHERE BKLOG=0

